### ISSUE TITLE
X11

### ISSUE THREAD

**Issue by hannesa2** [kurron/docker-charles-proxy#2]
When I try to run it with `docker-compose build && docker-compose up` I run into this

> charles    | /opt/ide/bin/charles: line 45: /opt/ide/bin/../lib/jre/bin/java: No such file or directory
> charles exited with code 1

Ok, I pointed out you download wrong architecture of Charles, so I switch to 64 bit Linux

`ADD https://www.charlesproxy.com/assets/release/4.2.1/charles-proxy-4.2.1_amd64.tar.gz /tmp/ide.tar.gz`

This first issue is gone, but now I run into

> Can't connect to X11 window server using 'unix:0.0' as the value of the DISPLAY variable.

I followed you suggestion
```
$ xhost +
access control disabled, clients can connect from any host
```

but issue still exists. Any ideas ?

**Comment by hannesa2** [comment]
it's related to PR https://github.com/kurron/docker-charles-proxy/pull/3

**Comment by kurron** [comment]
@hannesa2 I've started seeing this in my other Docker/GUI projects and haven't really dug into the problem yet.  I'll make sure to let you know once I figure out what is going on.
