### ISSUE TITLE
Denying access to Charles

### ISSUE THREAD

**Issue by bassani2014** [kurron/docker-charles-proxy#6]
Hi

I pulled down your image from docker and when i try to run it by doing the following:

docker run -d -p 8888:8888 --name container-charles kurron/docker-charles-proxy

It opens Charles but then denies the connection (see image). Any idea what could be causing the issue? Do i need to modify the config file mentioned https://www.charlesproxy.com/documentation/faqs/deploying-license-keys-during-installation/ ? If so do you know where the config file is kept only going into the container and navigating to the directory that's mentioned in the link above doesn't show the config file?

![issue](https://user-images.githubusercontent.com/6917985/170521799-fb74cac7-59fd-4609-933d-d97dc11e176c.png)

**Comment by kurron** [comment]
I haven't used this container in quite a while so I can't speculate on what might causing the issue.
